# -*- Makefile -*-
# Make rules for configuration files.
#

CFG             = kernel-$(VERSION)
KCONFIG		= python kconfig.py --merge

CONFIGFILES     = $(CFG)-i686.config $(CFG)-x86_64.config

OLDCONFIG	?= oldconfig

configs: $(CONFIGFILES)
	@rm -f kernel-*-config
	@rm -f $(TEMPFILES)

# Augment the clean target to clean up our own cruft
clean ::
	@rm -fv $(CONFIGFILES) kernel-$(VERSION)*config

kernel-$(VERSION)-i686.config: config-x86_32-generic config-generic
	@echo "# i386" > $@
	$(KCONFIG) $^ >>$@

kernel-$(VERSION)-x86_64.config: config-x86_64-generic config-generic
	@echo "# x86_64" > $@
	$(KCONFIG) $^ >>$@

NEWCONFIGS	= $(addprefix configs/,$(CONFIGFILES))

configs :
	@mkdir -p $@

$(NEWCONFIGS) : configs/% : % configs
	@cp -v $< .config
	Arch=$$(head -1 .config | cut -b 3-) ; make ARCH=$$Arch $(OLDCONFIG) ; echo "# $$Arch" >$@ ; cat .config >>$@

newconfigs: $(NEWCONFIGS)
